apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sml-internal-steward.fullname" . }}
data:
  git_ask_pass_script.sh: |-
{{- .Values.askPassScript | nindent 4 }}
  repos.md: |-
{{- .Values.repos | nindent 4 }}
