{{- if not .Values.existingSecretName }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "sml-internal-steward.fullname" . }}
data:
  GITHUB_TOKEN: {{ .Values.steward.githubToken | quote | b64enc  }}
{{- end }}

